"""Tab View 4: Data Export Hub & Policy Brief Center."""

import json
from typing import Tuple
import pandas as pd
import streamlit as st


def generate_policy_brief(
    center_lat: float,
    center_lon: float,
    cari_score: float,
    risk_tier: str,
    ndvi_obs: float,
    z_sm: float,
    z_lst: float,
) -> str:
    """Generate Markdown text for an executive Agricultural Policy Brief."""
    brief = f"""================================================================================
AGRI-SENS-CORE-V1: EXECUTIVE AGRICULTURAL RISK & POLICY BRIEF
================================================================================
Target Location: Latitude {center_lat:.4f}, Longitude {center_lon:.4f}
Assessment Date: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
================================================================================

1. EXECUTIVE RISK ASSESSMENT SUMMARY
--------------------------------------------------------------------------------
- Composite Agricultural Risk Index (CARI): {cari_score:.2f} / 100
- Risk Classification Tier:               [{risk_tier}]

2. SENSING METRIC BREAKDOWN
--------------------------------------------------------------------------------
- Observed Canopy Health (NDVI):          {ndvi_obs:.4f}
- Soil Moisture Deficit Z-Score (Z_SM):    {z_sm:+.2f} sigma
- Surface Temperature Anomaly (Z_LST):    {z_lst:+.2f} sigma

3. ACTIONABLE POLICY RECOMMENDATIONS
--------------------------------------------------------------------------------
"""
    if risk_tier == "NOMINAL":
        brief += """- Condition Nominal: Continue routine crop monitoring and standard irrigation schedules.
- Soil moisture and canopy levels are within normal seasonal parameters."""
    elif risk_tier == "MODERATE STRESS":
        brief += """- Early Warning Alert: Initiate weekly soil moisture monitoring.
- Prepare supplementary irrigation reserves and verify localized weather forecasts."""
    elif risk_tier == "HIGH RISK":
        brief += """- High Risk Protocol: Deploy localized agricultural Extension officers for field validation.
- Recommend targeted micro-irrigation and partial shading/mulching to mitigate thermal stress."""
    else:
        brief += """- CRITICAL EMERGENCY ALERT: Immediate disaster intervention required.
- Mobilize emergency drought relief funds, activate crop insurance payouts, and deliver emergency irrigation support."""

    brief += """

================================================================================
Generated by AGRI-SENS-CORE-V1 System Pipeline.
================================================================================
"""
    return brief


def render_export_tab(
    df: pd.DataFrame,
    center_lat: float,
    center_lon: float,
    bbox: Tuple[float, float, float, float],
    cari_score: float,
    risk_tier: str,
    ndvi_obs: float,
    z_sm: float,
    z_lst: float,
) -> None:
    """Render Data Export Hub & Policy Brief view."""
    st.subheader("📥 Data Export Center & Policy Brief Generator")
    st.markdown("Download field observations, spatial boundaries, and automated executive policy briefs.")

    col1, col2, col3 = st.columns(3)

    # 1. Export CSV
    with col1:
        st.markdown("### 📊 Time-Series Dataset (CSV)")
        st.write("Download complete preprocessed Sentinel-2 and NASA POWER time-series dataframe.")
        csv_data = df.to_csv(index=True).encode("utf-8")
        st.download_button(
            label="Download CSV Dataset",
            data=csv_data,
            file_name=f"agri_sens_timeseries_lat{center_lat:.2f}_lon{center_lon:.2f}.csv",
            mime="text/csv",
        )

    # 2. Export GeoJSON Boundary
    with col2:
        st.markdown("### 🗺️ AOI Boundary (GeoJSON)")
        st.write("Download field area of interest bounding polygon in standard GeoJSON format.")
        min_lon, min_lat, max_lon, max_lat = bbox
        geojson_struct = {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "properties": {
                        "cari_score": cari_score,
                        "risk_tier": risk_tier,
                        "center_lat": center_lat,
                        "center_lon": center_lon,
                    },
                    "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                            [
                                [min_lon, min_lat],
                                [max_lon, min_lat],
                                [max_lon, max_lat],
                                [min_lon, max_lat],
                                [min_lon, min_lat],
                            ]
                        ],
                    },
                }
            ],
        }
        geojson_json = json.dumps(geojson_struct, indent=2)
        st.download_button(
            label="Download GeoJSON Boundary",
            data=geojson_json,
            file_name=f"agri_sens_aoi_lat{center_lat:.2f}_lon{center_lon:.2f}.geojson",
            mime="application/json",
        )

    # 3. Export Policy Brief
    with col3:
        st.markdown("### 📜 Executive Policy Brief (TXT)")
        st.write("Download text policy brief summarizing risk tier, CARI score, and emergency recommendations.")
        policy_txt = generate_policy_brief(
            center_lat, center_lon, cari_score, risk_tier, ndvi_obs, z_sm, z_lst
        )
        st.download_button(
            label="Download Policy Brief",
            data=policy_txt,
            file_name=f"agri_sens_policy_brief_{risk_tier.lower().replace(' ', '_')}.txt",
            mime="text/plain",
        )
